### ISSUE TITLE
Component loses connection eventually

### ISSUE THREAD

**Issue by cgarwood** [bitfocus/companion-module-obsidiancontrol-onyx#5] opened 2020-02-07 19:31 UTC
On 2.0 with polling enabled the component will eventually lose its connection but not show an error. Feedback stops responding, button presses to trigger cues doesn't work.

Pulling up the companion config page and disabling/re-enabling the component will fix it for a while.

I'm going to do some troubleshooting on my dev setup to see if I can narrow down what's happening

**Comment by cgarwood** [comment] 2020-02-08 19:44
So, it appears that after a period of time, usually around 10-15 minutes on my dev setup, the telnet session either disconnects or freezes. No `data` events are fired and no commands are sent from Onyx when pushing a button on Companion. If it's disconnecting, no `end` event is ever fired and Companion will still show that it's connected on the Instances page.

I added logging to the `on("data")` function and it will just randomly get a response from Onyx that looks perfectly normal and then it never gets another set of data. No errors printed to the log or console. I'm not really sure what to try next.

**Comment by cgarwood** [comment] 2020-02-08 20:14
I just ran Wireshark my interface and can see the telnet commands getting sent out by Companion, and I can see the response from Onyx, but Companion isn't firing any `socket.on("data")` events for it.

**Comment by cgarwood** [comment] 2020-02-26 19:14
Here's a Wireshark capture. Companion stopped firing the `data` event around timestamp `1799` in the capture. Nothing about the packets around that time looks unusual to me, and you can see Companion is still sending data to the telnet server after that, just not processing anything it gets back.

[onyxcapture.zip](https://github.com/bitfocus/companion-module-obsidiancontrol-onyx/files/4257697/onyxcapture.zip)

**Comment by haakonnessjoen** [comment] 2020-02-26 21:01
Have you done debugging where you print out what you get immediately inside the on('data') event? Before any processing at all?

**Comment by cgarwood** [comment] 2020-02-26 21:02
OK from what I can tell it seems to be some sort of bug with the companion `telnet` module, but I have no idea what. Seems to be related to some kind of buffer filling up, but I was unable to locate the issue. If I turned the polling interval down (say by cutting it in half) the component would stop emitting `data` events in half the time. If I double the polling interval, it took twice as long to lose connection.

I switched the onyx component from the `telnet` module to the `tcp` module and it's been running fine for ~30 minutes. Going to give it a little longer then I'll commit the changes and submit a PR.

**Comment by cgarwood** [comment] 2020-02-26 21:06
@haakonnessjoen  just saw your comment after I submitted my previous comment. I did add a print line as the first line in the on('data') event, and it would stop being printed at the same time it stopped processing data, so it appears the data event is no longer being emitted.

I also added some debug lines to `telnetStream.prototype._getData` where it would print the buffer length. The weird thing there is it would actually stop printing the buffer length about 2 minutes in (but would still be receiving and processing data), and then about 4 minutes in it would stop emitting the `data` event all together. Saw the same behavior if I added logging to the `telnetStream.prototype._handleByte` function as well.

**Comment by haakonnessjoen** [comment] 2020-02-26 21:12
Weird stuff. Maybe I am using Stream.Transform in a wrong way or something. It might be something inside it that expects me to clear up some buffer or something, as you say. Would be nice to do some more testing, to try to figure out what the problem is.

**Comment by haakonnessjoen** [comment] 2020-02-26 21:25
In line 150 of telnet.js. Could you tro to change the following:
```	self.socket.on('data', self.emit.bind(self, 'data'));```

to:
```	self.ts.on('data', self.emit.bind(self, 'data'));```

**Comment by cgarwood** [comment] 2020-02-26 22:18
Switching from `self.socket.on('data'...` to `self.ts.on('data'...` has been good for about 30 minutes, where it was losing connection after about 8 minutes previously

**Comment by haakonnessjoen** [comment] 2020-02-26 22:37
Great stuff. Then we are fixing the same problem on all modules using the telnet module! That was an embarrasing bug! I will commit a bugfix to companion tomorrow!

**Comment by haakonnessjoen** [comment] 2020-02-27 08:24
Fixed by bitfocus/companion@dd6146b

**Closed as completed by haakonnessjoen** 2020-02-27 08:24 UTC
